cc_library (
    name = "aggresive-cows",
    srcs = ["aggresive-cows.cpp"],
    hdrs = ["aggresive-cows.h"],
)

cc_binary (
    name = "main",
    srcs = ["main.cpp"],
    deps = [
        ":aggresive-cows",
        "//lib:proconlib",
    ],
)
